# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sauron}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jaime Bellmyer"]
  s.date = %q{2010-07-18}
  s.description = %q{Speed up your automated tests with multiple databases and workers.}
  s.email = %q{jaime@kconrails.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.homepage = %q{http://github.com/bellmyer/sauron}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Multi-threaded, automated testing toolkit}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bellmyer-hydra>, [">= 0.20.9"])
      s.add_development_dependency(%q<watchr>, [">= 0.6"])
    else
      s.add_dependency(%q<bellmyer-hydra>, [">= 0.20.9"])
      s.add_dependency(%q<watchr>, [">= 0.6"])
    end
  else
    s.add_dependency(%q<bellmyer-hydra>, [">= 0.20.9"])
    s.add_dependency(%q<watchr>, [">= 0.6"])
  end
end

